# Generated by Django 6.0.7 on 2026-08-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="apartment_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Номер квартиры"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Город проживания"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Номер дома"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Укажите актуальный номер телефона",
                max_length=50,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите адрес электронной почты",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
