# Generated by Django 6.0.7 on 2026-07-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название категории"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название жанра"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание жанра"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название книги",
                        max_length=150,
                        verbose_name="Название книги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание книги"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(verbose_name="Количество книг"),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(max_length=150, verbose_name="Издатель"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/cover_image",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Укажите автора книги",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="author.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите жанр книги",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.genre",
                        verbose_name="Жанр книги",
                    ),
                ),
            ],
            options={
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
                "ordering": ["title"],
            },
        ),
    ]
