# Generated by Django 6.0.7 on 2026-08-02 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="category",
        ),
        migrations.AddField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Доступна ли книга для выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите жанр книги",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="genres",
                to="books.genre",
                verbose_name="Жанр книги",
            ),
        ),
        migrations.CreateModel(
            name="RentBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_issue",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата выдачи книги"
                    ),
                ),
                ("return_date", models.DateField(verbose_name="Дата возврата книги")),
                (
                    "is_returned",
                    models.BooleanField(
                        default=False, verbose_name="Флаг возврата книги"
                    ),
                ),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        help_text="Срок аренды в днях", verbose_name="Срок аренды"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Укажите книгу которую пользователь берет для чтения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Читатель книги",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Читатель книги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аренда книги",
                "verbose_name_plural": "Аренды книг",
                "ordering": ["pk"],
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
