# Generated by Django 6.0.7 on 2026-08-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_genre_category_book_is_available_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentbooks",
            old_name="user",
            new_name="reader",
        ),
    ]
