# Generated by Django 6.0.7 on 2026-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_rename_user_rentbooks_reader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentbooks",
            name="return_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата возврата книги"
            ),
        ),
    ]
