# Generated by Django 6.0.7 on 2026-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_rentbooks_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="available_quantity",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Доступное количество книг"
            ),
            preserve_default=False,
        ),
    ]
