# Generated by Django 6.0.7 on 2026-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_available_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentbooks",
            name="term",
        ),
        migrations.AddField(
            model_name="rentbooks",
            name="deadline",
            field=models.DateField(
                default="2026-08-03",
                help_text="Укажите крайний срок сдачи книги в формате YYYY-MM-DD",
                verbose_name="Крайний срок сдачи книги",
            ),
            preserve_default=False,
        ),
    ]
