# Generated by Django 6.0.7 on 2026-08-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_remove_rentbooks_term_rentbooks_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentbooks",
            old_name="reader",
            new_name="user",
        ),
    ]
