# Generated by Django 6.0.7 on 2026-07-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя автора",
                        max_length=150,
                        verbose_name="Имя автора",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию автора",
                        max_length=150,
                        verbose_name="Фамилия автора",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату рождения в формате YYYY-MM-DD",
                        null=True,
                        verbose_name="Дата рождения автора",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Напишите биографию автора",
                        null=True,
                        verbose_name="Биография автора",
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату смерти в формате YYYY-MM-DD",
                        null=True,
                        verbose_name="Дата смерти автора",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Укажите страну где проживал автор",
                        max_length=100,
                        null=True,
                        verbose_name="Страна проживания автора",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Укажите родной язык автора",
                        max_length=100,
                        null=True,
                        verbose_name="Родной язык автора",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото или изображение автора",
                        null=True,
                        upload_to="author/photo",
                        verbose_name="Фото или изображение автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
    ]
